web:
  user: user
  build: .
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
  dockerfile: Dockerfile
  tty: true
  stdin_open: true
  ports:
    - "3001:3001"
  expose:
    - "3001"
  env_file:
    - .env
  links:
    - db
    - redis
    - sidekiq
  volumes:
    - ".:/ecommerce-api"
db:
  image: postgres
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  ports: ["5432:5432"]
  expose: ["5432"]

redis:
  image: redis:latest
  command: redis-server
  volumes:
  - 'redis:/data'
  env_file:
    - .env
  links:
    - db

sidekiq:
  build: .
  command: sidekiq
  volumes:
    - ".:/ecommerce-api"
  env_file:
    - .env
  links:
    - db
    - redis
