web:
  user: user
  build: .
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
  dockerfile: Dockerfile
  tty: true
  stdin_open: true
  ports:
    - "3001:3001"
  expose:
    - "3001"
  environment:
    - RAILS_ENV=development
    - API_AUTHORIZATION=development
  links:
    - db
  volumes:
    - ".:/ecommerce-api"
db:
  image: postgres
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  ports: ["5432:5432"]
  expose: ["5432"]
